module.exports = [
  {
    id: 7000,
    name: 'Uncharted',
    type: 'action',
    img: 'IMG/Uncharted4.jpg',
    part: 4,
    year: 2016,
    commingSoon: 0,
    finished: 2,
    platform: 'PS4',
    date: 20210907
  },
  {
    id: 7001,
    name: 'Dark Souls Remaster',
    type: 'arpg',
    img: 'IMG/DarkSouls.jpg',
    part: 1,
    year: 2018,
    commingSoon: 0,
    finished: 2,
    watched: 'PS4',
    date: 20200702
  },
  {
    id: 7002,
    name: 'Dead Cells',
    type: 'rogalik',
    img: 'IMG/DeadCells.jpg',
    part: 0,
    year: 2018,
    commingSoon: 0,
    finished: 2,
    watched: 'NS',
    date: 20200702
  },
  {
    id: 7003,
    name: 'Shovel Knight',
    type: 'platformer',
    img: 'IMG/ShovelKnight.jpg',
    part: 0,
    year: 2017,
    commingSoon: 0,
    finished: 2,
    watched: 'NS',
    date: 20191021
  },
  {
    id: 7004,
    name: 'Borderlands 2',
    type: 'fps',
    img: 'IMG/Borderlands2.jpg',
    part: 2,
    year: 2012,
    commingSoon: 0,
    finished: 2,
    watched: 'PS4',
    date: 20211111
  },
  {
    id: 7005,
    name: 'Zelda: Breath of the Wild',
    type: 'action',
    img: 'IMG/ZeldaBotW.jpg',
    part: 1,
    year: 2017,
    commingSoon: 1,
    finished: 1,
    watched: 'NS',
    date: 20211223
  },
  {
    id: 7006,
    name: 'Remnant: From the Ashes',
    type: 'fps',
    img: 'IMG/Remnant.jpg',
    part: 1,
    year: 2019,
    commingSoon: 0,
    finished: 2,
    watched: 'PS4',
    date: 20211112
  },
  {
    id: 7007,
    name: 'Witcher 3 Blood and Wine',
    type: 'rpg',
    img: 'IMG/BloodAndWine.jpg',
    part: 3,
    year: 2016,
    commingSoon: 0,
    finished: 2,
    watched: 'PS4',
    date: 20220129
  },
  {
    id: 7008,
    name: 'The Last of Us',
    type: 'action',
    img: 'IMG/TLoU.png',
    part: 1,
    year: 2013,
    commingSoon: 0,
    finished: 0,
    watched: 'PS4',
    date: 20211223
  },
  {
    id: 7009,
    name: 'Bloodborne',
    type: 'arpg',
    img: 'IMG/BloodborneTOH.jpg',
    part: 1,
    year: 2015,
    commingSoon: 0,
    finished: 0,
    watched: 'PS4',
    date: 20211222
  },
  {
    id: 7010,
    name: 'Dark Souls II',
    type: 'arpg',
    img: 'IMG/DarkSouls2.jpg',
    part: 2,
    year: 2014,
    commingSoon: 0,
    finished: 1,
    watched: 'PS4',
    date: 20210222
  },
  {
    id: 7011,
    name: 'Cyberpunk2077',
    type: 'rpg',
    img: 'IMG/Cyberpunk2077.jpg',
    part: 1,
    year: 2020,
    commingSoon: 0,
    finished: 1,
    watched: 'STI',
    date: 20211207
  },
  {
    id: 7012,
    name: 'God of War',
    type: 'action',
    img: 'IMG/GodOfWar.jpg',
    part: 4,
    year: 2018,
    commingSoon: 0,
    finished: 0,
    watched: 'PS4',
    date: 20211227
  },
  {
    id: 7013,
    name: 'Assasins Creed: Black Flag',
    type: 'action',
    img: 'IMG/BlackFlag.jpg',
    part: 4,
    year: 2013,
    commingSoon: 0,
    finished: 0,
    watched: 'STI',
    date: 20220101
  },
  {
    id: 7014,
    name: 'Frostpunk',
    type: 'strategy',
    img: 'IMG/Frostpunk.jpg',
    part: 1,
    year: 2018,
    commingSoon: 1,
    finished: 2,
    watched: 'PS4',
    date: 20210227
  },
  {
    id: 7015,
    name: 'Deep Rock Galactic',
    type: 'Action',
    img: 'IMG/DeepRock.jpg',
    part: 0,
    year: 2018,
    commingSoon: 0,
    finished: 1,
    watched: 'PS4',
    date: 20220110
  },
  {
    id: 7016,
    name: 'Red Dead Redemption 2',
    type: 'Action',
    img: 'IMG/RedDeadR2.jpg',
    part: 2,
    year: 2018,
    commingSoon: 0,
    finished: 0,
    watched: 'PS4',
    date: 20200100
  },
  {
    id: 7017,
    name: 'Horizon 2',
    type: 'Action',
    img: 'IMG/Horizon.jpg',
    part: 2,
    year: 2017,
    commingSoon: 1,
    finished: 0,
    watched: 'PS4',
    date: 20201100
  },
  {
    id: 7018,
    name: 'Gran Turismo',
    type: 'Racing',
    img: 'IMG/GranTurismo.jpg',
    part: 7,
    year: 2022,
    commingSoon: 1,
    finished: 0,
    watched: 'PS5',
    date: 20220310
  },
  {
    id: 7019,
    name: 'Horizon Zero Dawn',
    type: 'Action',
    img: 'IMG/HorizonZD.jpg',
    part: 1,
    year: 2017,
    commingSoon: 1,
    finished: 1,
    watched: 'PS5',
    date: 20220207
  },
  {
    id: 7020,
    name: 'Astros Playroom',
    type: 'Platform',
    img: 'IMG/AstroPlayroom.png',
    part: 0,
    year: 2020,
    commingSoon: 0,
    finished: 2,
    watched: 'PS5',
    date: 20220203
  },
  {
    id: 7021,
    name: 'Death Stranding',
    type: 'action',
    img: 'IMG/DeathStranding.jpg',
    part: 0,
    year: 2019,
    commingSoon: 0,
    finished: 0,
    watched: 'PS5',
    date: 20220101
  }
];
