module.exports = [
  {
    id: 100,
    name: 'Alice in Borderlands',
    type: 'series',
    img: 'IMG/AliceInBorderlands.jpg',
    part: 1,
    year: 2021,
    commingSoon: 1,
    finished: 2,
    watched: 'Netflix',
    date: 20211107
  },
  {
    id: 101,
    name: 'Star Wars: Rebels',
    type: 'series',
    img: 'IMG/Rebels.jpg',
    part: 4,
    year: 2017,
    commingSoon: 0,
    finished: 2,
    watched: 'Disney+',
    date: 20210917
  },
  {
    id: 102,
    name: 'Dune',
    type: 'movie',
    img: 'IMG/Dune.jpg',
    part: 1,
    year: 2021,
    commingSoon: 1,
    finished: 2,
    watched: 'Cinema',
    date: 20211027
  },
  {
    id: 103,
    name: 'Arrival',
    type: 'movie',
    img: 'IMG/Arrival.jpg',
    part: 0,
    year: 2016,
    commingSoon: 0,
    finished: 2,
    watched: 'Netflix',
    date: 20211024
  },
  {
    id: 104,
    name: 'Arcane',
    type: 'series',
    img: 'IMG/Arcane.jpg',
    part: 1,
    year: 2021,
    commingSoon: 0,
    finished: 2,
    watched: 'Netflix',
    date: 20211129
  },
  {
    id: 105,
    name: 'Warcraft',
    type: 'movie',
    img: 'IMG/Warcraft.jpg',
    part: 0,
    year: 2016,
    commingSoon: 0,
    finished: 2,
    watched: 'Cinema',
    date: 20160624
  },
  {
    id: 106,
    name: 'Chernobyl',
    type: 'series',
    img: 'IMG/Chernobyl.jpeg',
    part: 0,
    year: 2021,
    commingSoon: 0,
    finished: 2,
    watched: 'HBO',
    date: 20191020
  },
  {
    id: 107,
    name: 'Joker',
    type: 'movie',
    img: 'IMG/Joker.jpg',
    part: 0,
    year: 2021,
    commingSoon: 0,
    finished: 2,
    watched: 'Amazon',
    date: 20200614
  },
  {
    id: 108,
    name: 'The Boys',
    type: 'series',
    img: 'IMG/theboys.jpg',
    part: 2,
    year: 2021,
    commingSoon: 0,
    finished: 2,
    watched: 'Amazon',
    date: 20211211
  },
  {
    id: 109,
    name: 'Solar Opposites',
    type: 'series',
    img: 'IMG/SolarOpposites.jpg',
    part: 1,
    year: 2020,
    commingSoon: 1,
    finished: 1,
    watched: 'Hulu',
    date: 20211217
  },
  {
    id: 110,
    name: 'Dragon Ball',
    type: 'series',
    img: 'IMG/DragonBall.jpg',
    part: 1,
    year: 2020,
    commingSoon: 0,
    finished: 2,
    watched: 'DVD',
    date: 20211101
  }
];
