export const labelsPL = {
  placeholderNavSeries: 'seriale',
  placeholderNavHome: 'home',
  placeholderNavVideo: 'wideo',
  placeholderNavGames: 'gry',
  placeholderNavAktualne: 'aktualne',
  placeholderNavCatchUp: 'kupka wstydu',
  placeholderNavCommingSoon: 'nadchodzace',
  placeholderNavUkonczone: 'ukonczone',
  modalNoWiki: 'Nie znaleziono wiki dla ',
  modalCloseButton: 'ZAMKNIJ MODAL',
  modalReleased: 'Wydane ',
  modalSeenAt: 'Widziales to ',
  itemPart: 'Czesc',
  itemSeason: 'Sezon',
  footerCopyRights: '© 2022 Listownik by Kuba',
  footerHere: 'Footer here',
  error404: 'Blad 404 Strona nie zadowolona',
  errorDescribtion: `It's working anyway`,
  posterText: 'Jakis tekst',
  shelfSeen: 'Widziane'
};
