export const labelsPL = {
  navSeries: 'seriale',
  navHome: 'home',
  navVideo: 'wideo',
  navGames: 'gry',
  navCurrent: 'aktualne',
  navCatchUp: 'kupka wstydu',
  navCommingSoon: 'nadchodzace',
  navFinished: 'ukonczone',
  formModalHeader: 'Add new Poster',
  modalNoWiki: 'Nie znaleziono wiki dla ',
  modalCloseButton: 'ZAMKNIJ MODAL',
  modalReleased: 'Wydane ',
  modalSeenAt: 'Widziales to ',
  itemPart: 'Czesc',
  itemSeason: 'Sezon',
  footerCopyRights: '© 2022 Listownik by Kuba',
  footerHere: 'Footer here',
  error404: 'Blad 404 Strona nie zadowolona',
  errorDescribtion: `It's working anyway`,
  posterText: 'Jakis tekst',
  shelfSeen: 'Widziane'
};
